import type { CategoryCode } from "../gql/graphql";

export const categoryOptions: { label: string; value: CategoryCode }[] = [
  { label: "憲法", value: "CONSTITUTION" }, // 001
  { label: "刑事", value: "CRIMINAL" }, // 002
  { label: "財務通則", value: "FINANCE_GENERAL" }, // 003
  { label: "水産業", value: "FISHERIES" }, // 004
  { label: "観光", value: "TOURISM" }, // 005
  { label: "国会", value: "PARLIAMENT" }, // 006
  { label: "警察", value: "POLICE" }, // 007
  { label: "国有財産", value: "NATIONAL_PROPERTY" }, // 008
  { label: "鉱業", value: "MINING" }, // 009
  { label: "郵務", value: "POSTAL_SERVICE" }, // 010
  { label: "行政組織", value: "ADMINISTRATIVE_ORG" }, // 011
  { label: "消防", value: "FIRE_SERVICE" }, // 012
  { label: "国税", value: "NATIONAL_TAX" }, // 013
  { label: "工業", value: "INDUSTRY" }, // 014
  { label: "電気通信", value: "TELECOMMUNICATIONS" }, // 015
  { label: "国家公務員", value: "CIVIL_SERVICE" }, // 016
  { label: "国土開発", value: "NATIONAL_DEVELOPMENT" }, // 017
  { label: "事業", value: "BUSINESS" }, // 018
  { label: "商業", value: "COMMERCE" }, // 019
  { label: "労働", value: "LABOR" }, // 020
  { label: "行政手続", value: "ADMINISTRATIVE_PROC" }, // 021
  { label: "土地", value: "LAND" }, // 022
  { label: "国債", value: "NATIONAL_BONDS" }, // 023
  { label: "金融・保険", value: "FINANCE_INSURANCE" }, // 024
  { label: "環境保全", value: "ENVIRONMENTAL_PROTECT" }, // 025
  { label: "統計", value: "STATISTICS" }, // 026
  { label: "都市計画", value: "CITY_PLANNING" }, // 027
  { label: "教育", value: "EDUCATION" }, // 028
  { label: "外国為替・貿易", value: "FOREIGN_EXCHANGE_TRADE" }, // 029
  { label: "厚生", value: "PUBLIC_HEALTH" }, // 030
  { label: "地方自治", value: "LOCAL_GOVERNMENT" }, // 031
  { label: "道路", value: "ROADS" }, // 032
  { label: "文化", value: "CULTURE" }, // 033
  { label: "陸運", value: "LAND_TRANSPORT" }, // 034
  { label: "社会福祉", value: "SOCIAL_WELFARE" }, // 035
  { label: "地方財政", value: "LOCAL_FINANCE" }, // 036
  { label: "河川", value: "RIVERS" }, // 037
  { label: "産業通則", value: "INDUSTRY_GENERAL" }, // 038
  { label: "海運", value: "MARITIME_TRANSPORT" }, // 039
  { label: "社会保険", value: "SOCIAL_INSURANCE" }, // 040
  { label: "司法", value: "JUDICIARY" }, // 041
  { label: "災害対策", value: "DISASTER_MANAGEMENT" }, // 042
  { label: "農業", value: "AGRICULTURE" }, // 043
  { label: "航空", value: "AVIATION" }, // 044
  { label: "防衛", value: "DEFENSE" }, // 045
  { label: "民事", value: "CIVIL" }, // 046
  { label: "建築・住宅", value: "BUILDING_HOUSING" }, // 047
  { label: "林業", value: "FORESTRY" }, // 048
  { label: "貨物運送", value: "FREIGHT_TRANSPORT" }, // 049
  { label: "外事", value: "FOREIGN_AFFAIRS" }, // 050
];
